### ISSUE TITLE
geo标签不正常

### ISSUE THREAD

**Issue by mzcinf** [justan/t2w#1]
每次都被定位到印度。

**Comment by mzcinf** [comment]
geo: { type: 'Point', coordinates: [ 39.109805, 117.158215 ] },
coordinates: { type: 'Point', coordinates: [ 117.158215, 39.109805 ] },
coordinates: [ 73.602256307, 15.7753766950001 ],
日志里拿出来的

**Comment by justan** [comment]
@9ft 
不知道是不是两边的 geo 接口没有对上
可以看下微博的接口:
http://open.weibo.com/wiki/2/statuses/update
以及发送时的调用
https://github.com/justan/twei/blob/master/lib/twei.js#L34
